source "https://rubygems.org"
ruby "3.3.4"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "sidekiq", "~> 7.2"
gem "faraday", "~> 2.9"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "rubocop", "~> 1.60"
  gem "factory_bot_rails", "~> 6.4"
end
